@startuml
skinparam defaultFontName Courier
skinparam monochrome true
skinparam shadowing false

class Project {
	RootPackage    *Package
	BuildArtifacts []BuildArtifact
	Name           string
}

class BuildArtifact  {
	BuildPackageName string
	BuildArgs        []string
	LinkerArgs       []string
	OutputFile       string
}

class Package {
	Name     string
	Children []*Package
	Files    []*SourceFile
	Parent   *Package
}
                 
class SourceFile {
	Name     string
	Language string
	Package  *Package

	Imports      []PackageImport
	Declarations []Declaration
}

class Import {
	Pkg *Package
}

class ExternalImport {
	PathName string
}

interface PackageImport {

}

              

Project o-- Package
Project *-- BuildArtifact
Package *-- SourceFile
SourceFile *-- PackageImport
PackageImport <|-- Import
PackageImport <|-- ExternalImport

@enduml
